[theme]
# A dark-blue primary accent color for interactive elements
primaryColor = "#a1750d"

# A light "white-blue" background color for the main content area
backgroundColor = "#eee2dc"

# A lighter background color for the sidebar and other components
secondaryBackgroundColor = "#ffffff"

# A darker text color for better contrast against the light background
textColor = "#000000"
